### ISSUE TITLE
Uncaught TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by turcuciprian** [amitmtrn/atom-ftp-editor#10]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [atom-ftp-editor](https://github.com/amitmtrn/atom-ftp-editor) package, v0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'file' of undefined

```
At /Users/turcuciprian/.atom/packages/atom-ftp-editor/lib/main.js:122

TypeError: Cannot read property 'file' of undefined
    at Object.module.exports.AtomFtpEditor.__getCurrentFile (/Users/turcuciprian/.atom/packages/atom-ftp-editor/lib/main.js:122:60)
    at atom-workspace.module.exports.AtomFtpEditor.currentDownload (/Users/turcuciprian/.atom/packages/atom-ftp-editor/lib/main.js:57:35)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1019:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:143:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:250:47)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:00.7.0 ftp-editor:current-download (span.name.icon.icon-file-directory)
```

### Config

```json
{
  "core": {},
  "atom-ftp-editor": {}
}
```

### Installed Packages

```coffee
# User
atom-ftp-editor, v0.5.0
color-picker, v2.0.14
minimap, v4.19.0
quick-highlight, v0.3.10

# Dev
No dev packages
```

**Comment by Mandrilux** [comment]
i have same problem

**Comment by AkashM08** [comment]
I am also facing same issue.

Can anyone help me out how to get resolve this issue.

**Comment by sulemankhan1** [comment]
ihave same problem

**Comment by stephenchaffins** [comment]
ditto on the problem

**Comment by mehdibo** [comment]
Same problem here

**Comment by MartinPutz** [comment]
I have the same problem

**Comment by ratatyq** [comment]
I have the same problem, 
atom version: 1.19.2
os: windows 10 x64
