### ISSUE TITLE
Uncaught TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by iosifnicolae2** [amitmtrn/atom-ftp-editor#3]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Linux Mint
**Thrown From**: [atom-ftp-editor](https://github.com/amitmtrn/atom-ftp-editor) package, v0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'get' of undefined

```
At /home/iosif/.atom/packages/atom-ftp-editor/lib/main.js:248

TypeError: Cannot read property 'get' of undefined
  at Object.module.exports.AtomFtpEditor.__download (/home/iosif/.atom/packages/atom-ftp-editor/lib/main.js:248:28)
  at /home/iosif/.atom/packages/atom-ftp-editor/lib/main.js:252:25
  at Object.cb (/home/iosif/.atom/packages/remote-sync/node_modules/ftp/lib/connection.js:606:15)
  at Parser.<anonymous> (/home/iosif/.atom/packages/remote-sync/node_modules/ftp/lib/connection.js:113:22)
  at emitTwo (events.js:87:13)
  at Parser.emit (events.js:169:7)
  at Parser._write (/home/iosif/.atom/packages/remote-sync/node_modules/ftp/lib/parser.js:59:10)
  at doWrite (_stream_writable.js:295:12)
  at writeOrBuffer (_stream_writable.js:282:5)
  at Parser.Writable.write (_stream_writable.js:210:11)
  at Socket.ondata (/home/iosif/.atom/packages/remote-sync/node_modules/ftp/lib/connection.js:273:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at TCP.onread (net.js:517:20)

```

### Commands

```
     -9:52.5.0 atom-ftp-deployment:start-deployment (atom-workspace.workspace.scrollbars-visible-always.theme-atom-light-syntax.theme-atom-light-ui)
     -1:18.9.0 core:cancel (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
     -1:06.7.0 ftp-editor:create (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:41.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:40.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:17.8.0 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:00.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "language-hyperlink",
      "autocomplete-plus",
      "autosave",
      "bracket-matcher",
      "fuzzy-finder",
      "grammar-selector",
      "autocomplete-html"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ftp-editor, v0.5.0
autoclose-html, v0.18.0

# Dev
No dev packages
```

**Comment by amitmtrn** [comment]
How did you encounter the issue? please provide steps to reproduce.
