### ISSUE TITLE
Failed to activate the atom-ftp-editor package

### ISSUE THREAD

**Issue by rodrigopulse** [amitmtrn/atom-ftp-editor#4]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.5
**System**: Mac OS X 10.9.4
**Thrown From**: [atom-ftp-editor](https://github.com/amitmtrn/atom-ftp-editor) package, v0.5.0

### Stack Trace

Failed to activate the atom-ftp-editor package

```
At Cannot find module 'atom://config/.ftp-settings.json'

Error: Cannot find module 'atom://config/.ftp-settings.json'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.module.exports.AtomFtpEditor.__createFTP (/Users/rodrigo/.atom/packages/atom-ftp-editor/lib/main.js:103:32)
  at module.exports.AtomFtpEditor.__onopen (/Users/rodrigo/.atom/packages/atom-ftp-editor/lib/main.js:82:21)
  at PaneContainer.module.exports.PaneContainer.observePaneItems (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:126:9)
  at Object.module.exports.AtomFtpEditor.activate (/Users/rodrigo/.atom/packages/atom-ftp-editor/lib/main.js:52:36)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:243:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:836:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -0:01.3.0 ftp-editor:create (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-ftp-editor, v0.5.0
emmet, v2.3.12
less-autocompile, v1.0.0

# Dev
No dev packages
```

**Comment by amitmtrn** [comment]
please provide steps to reproduce the error.

**Comment by datanotion** [comment]
It just happened to me as well.  I'm on OSX.  Installed, then selected "Create and Initialize Settings".  Nothing seemed to have happened, so I tried it again.  Nothing.  So I restarted Atom, and selected "Create and Initialize Settings" again - thats when I receive the error message.

In case it might help, I had also installed the "Remote-FTP" package at the same time to compare with, but I have not set it up yet.

Thx.

**Comment by amitmtrn** [comment]
I will release the next version in the next week so I hope that most of the issues will be solved by then.
the create and initialize settings create a setting file in your project folder the project file need to be edited with your ftp settings it's not that comfortable and I think that a lot of people don't understand the flow and that's what cause the issues ...

**Comment by ricardo-vargas** [comment]
Happened to me as well.

**Comment by exantas** [comment]
Me too same error...

**Comment by ivanneira** [comment]
same error

**Comment by BluTiger** [comment]
Same for me. Just installed and this is what came up.

**Comment by spirit986** [comment]
Same here I am on Windows...
I downloaded the package, and from the menu clicked Packages -> FTP Editor -> Create and Initialize settings ..

I tried restarting atom, no luck ..

**Comment by jimmcnulty41** [comment]
Still happening on Windows at least. Tried to Create and Initialize and happened the very first time

**Comment by v2belleville** [comment]
Same problem : windows 7 pro. git installed then  Packages -> FTP Editor -> Create and Initialize settings ..

![atom-ftp-editor error](https://cloud.githubusercontent.com/assets/8779004/21557769/5b280706-ce31-11e6-94ab-dad8f369ba82.PNG)

Hope you can fix it! package looked promising !

Best

**Comment by Vis25** [comment]
Same problem : Arch Linux - (Antegros Linux).
![kuvakaappaus 2017-01-20 13-02-53](https://cloud.githubusercontent.com/assets/17277707/22147370/f731a568-df10-11e6-90c5-128e85faef46.png)
