### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by cbwiedel** [amitmtrn/atom-ftp-editor#5]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.4
**Thrown From**: [atom-ftp-editor](https://github.com/amitmtrn/atom-ftp-editor) package, v0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/calebwiedel/.atom/packages/atom-ftp-editor/lib/main.js:115

TypeError: Cannot read property 'path' of undefined
  at Object.module.exports.AtomFtpEditor.__uploadCurrent (/Users/calebwiedel/.atom/packages/atom-ftp-editor/lib/main.js:115:84)
  at atom-workspace.module.exports.AtomFtpEditor.currentUpload (/Users/calebwiedel/.atom/packages/atom-ftp-editor/lib/main.js:70:21)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:157:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -2:41.4.0 application:new-file (atom-text-editor.editor.is-focused)
     -2:39.5.0 core:paste (atom-text-editor.editor.is-focused)
     -2:35.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:58.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-material-syntax.theme-atom-material-ui)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.11
atom-ftp-editor, v0.5.0
atom-material-syntax, v0.2.3
atom-material-ui, v0.6.0
autoclose-html, v0.19.0
emmet, v2.3.12
minimap, v4.13.3
pigments, v0.14.0
remote-edit, v1.8.18

# Dev
No dev packages
```

**Comment by cyruswhyte** [comment]
same thing happening to me on Windows 10

**Comment by orkank** [comment]
same here

mac os x el capitan, atom 1.0.19

**Comment by pvtmashkov** [comment]
same here on Windows 10

**Comment by Thalles** [comment]
How are the settings?

**Comment by naeluh** [comment]
In /.atom/packages/atom-ftp-editor/lib/main.js

Change this:

`AtomFtpEditor.__upload(AtomFtpEditor.__getCurrentFile(), AtomFtpEditor.settings.path + cleanPath);	`

to

`if (AtomFtpEditor.settings.path !== undefined) {
     AtomFtpEditor.__upload(AtomFtpEditor.__getCurrentFile(), AtomFtpEditor.settings.path + cleanPath);	
}`

That should fix then error

**Comment by Thalles** [comment]
Thanks
