### ISSUE TITLE
Uncaught TypeError: Cannot read property 'buffer' of undefined

### ISSUE THREAD

**Issue by pvtmashkov** [amitmtrn/atom-ftp-editor#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Microsoft Windows 10 Home
**Thrown From**: [atom-ftp-editor](https://github.com/amitmtrn/atom-ftp-editor) package, v0.5.0

### Stack Trace

Uncaught TypeError: Cannot read property 'buffer' of undefined

```
At C:\Users\Sander\.atom\packages\atom-ftp-editor\lib\main.js:122

TypeError: Cannot read property 'buffer' of undefined
    at Object.module.exports.AtomFtpEditor.__getCurrentFile (C:\Users\Sander\.atom\packages\atom-ftp-editor\lib\main.js:122:53)
    at atom-workspace.module.exports.AtomFtpEditor.currentDownload (C:\Users\Sander\.atom\packages\atom-ftp-editor\lib\main.js:57:35)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Sander\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\Sander\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\Sander\AppData\Local\atom\app-1.2.4\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (C:\Users\Sander\AppData\Local\atom\app-1.2.4\resources\app.asar\src\atom-environment.js:993:28)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at EventEmitter.ipc.sendSync (C:\Users\Sander\AppData\Local\atom\app-1.2.4\resources\atom.asar\renderer\api\lib\ipc.js:21:31)
    at BrowserWindow.RemoteMemberFunction [as emit] (C:\Users\Sander\AppData\Local\atom\app-1.2.4\resources\atom.asar\renderer\api\lib\remote.js:138:29)
    at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (C:\Users\Sander\AppData\Local\atom\app-1.2.4\resources\app.asar\src\context-menu-manager.js:156:33)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentContextmenu (C:\Users\Sander\AppData\Local\atom\app-1.2.4\resources\app.asar\src\window-event-handler.js:252:47)
    at HTMLDocument.<anonymous> (C:\Users\Sander\AppData\Local\atom\app-1.2.4\resources\app.asar\src\window-event-handler.js:3:61)
```

### Commands

```
     -2:17.9.0 core:select-left (atom-text-editor.editor.is-focused)
     -2:15.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:15.1.0 core:delete (atom-text-editor.editor.is-focused)
     -2:14.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:11.9.0 core:copy (atom-text-editor.editor.is-focused)
     -2:10 core:paste (atom-text-editor.editor.is-focused)
     -1:59.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:56.3.0 core:save (atom-text-editor.editor.is-focused)
  2x -1:50.7.0 tree-view:move (span.name.icon.icon-file-directory)
     -1:39.4.0 project-find:show-in-current-directory (span.name.icon.icon-file-directory)
     -1:33.8.0 core:cancel (atom-pane.pane.active)
     -1:28.6.0 atom-beautify:beautify-editor (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:21.2.0 dev-live-reload:reload-all (atom-pane.pane.active)
     -1:14.1.0 remote-ftp:connect (atom-pane.pane.active)
  4x -0:44.4.0 remote-ftp:toggle (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:03.5.0 ftp-editor:current-download (span.name.icon.icon-file-directory)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "remote-sync"
    ],
    "projectHome": "C:\\xampp\\htdocs",
    "openEmptyEditorOnStart": false
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.19
atom-ftp-editor, v0.5.0
autoclose-html, v0.19.0
autocomplete-paths, v1.0.2
color-picker, v2.0.14
file-icons, v1.6.13
jshint, v1.8.3
language-twig, v1.6.2
php-cs-fixer, v2.5.1
remote-edit, v1.8.22
Remote-FTP, v0.7.14

# Dev
No dev packages
```

**Comment by Caprini** [comment]
I have this issue too...  Finally you can solve?
